
---
- name: Install Docker on Ubuntu
  hosts: localhost
  become: true

  tasks:
    - name: Update the packages
      command: apt update

    - name: Install Docker
      command: apt install -y docker.io

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'

    - name: Add the Docker group to the user
      user:
        name: "ubuntu"
        groups: docker
        append: yes
        
