
---
- name: Install Docker on Ubuntu
  hosts: localhost
  become: true

  tasks:
    - name: Update the packages
      command: apt update

    - name: Install Docker
      command: apt install -y docker.io

    - name: Enable Docker service
      command: systemctl enable docker

    - name: Start Docker service
      command: systemctl start docker

    - name: Add the Docker group to the user
      user:
        name: "ubuntu"
        groups: docker
        append: yes